### ISSUE TITLE
Wireframes Low-Fi

### ISSUE THREAD

**Issue by RileyBlue** [Uchiha-Society/uchiha-podcast#1]
Antes de pasar a los Wireframes de Alta Calidad y previo a los Mockups, me gustaría saber qué te parece la estructura, si hace falta añadir algo o si para iniciar está bien. :B @UchihaCFC

**Comment by RileyBlue** [comment]
![podcast-vista-general](https://user-images.githubusercontent.com/2449009/45592421-99860280-b932-11e8-97cd-a919d8d0edc9.jpg)

Wireframe de baja calidad: Vista general home

**Comment by RileyBlue** [comment]
![podcast-vista-interior](https://user-images.githubusercontent.com/2449009/45592423-ac003c00-b932-11e8-904a-c81209a028e6.jpg)

Wireframe de baja calidad: Vista interna de podcast

**Comment by UchihaCFC** [comment]
me encanta o,o! única cosa que no entiendo, para poder escuchar los podcast, tendremos registro de user o algo así?

**Comment by RileyBlue** [comment]
Oh, vale, vale. Sí, llegué a contemplar un sistema de login para que la gente pudiese comentar o guardar sus podcasts favoritos, pero creo que para comenzar... Dejemos el login en una segunda etapa. ¿Va?

**Comment by UchihaCFC** [comment]
No lo decía por que fuera más trabajo, ni nada para empezar. Simplemente para tener en cuenta la ley de protección de datos y la politica de privacidad nueva xD habrá que hacer una sección de eso si ponemos registro

**Comment by RileyBlue** [comment]
Tienes razón, bueno, igual... Qué mejor que mantenerlo todo más simple. (:
